version: '3.8'
services:
  mdbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    command: "mdbook serve --hostname '0.0.0.0'"
    working_dir: "/workdir"
    volumes:
      - "./:/workdir"
      - "./.vimrc:/root/.vimrc"
